global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using SurveyBasket.API.Resource;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SurveyBasket.API.Repository.BaseRopository;
global using Mapster;
global using SurveyBasket.API.DTOs.Requests;
global using SurveyBasket.API.DTOs.Responses;